In [67]:
import numpy as np

In [68]:
testMat = np.eye(4)
testMat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

***
np.nonzero test
返回不为零索引，分维度返回

In [69]:
np.nonzero(testMat)

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [70]:
np.nonzero([1,0,1])

(array([0, 2]),)

In [71]:
np.nonzero([[0,0],
            [1,0],
            [0,1]])
# index (1,0) (2, 1)不为零

(array([1, 2]), array([0, 1]))

In [72]:
np.nonzero([[[1]],
            [[0]],
            [[1]]])

# 三维数组 
# index (0，0，0) （2， 0， 0）不为零

(array([0, 2]), array([0, 0]), array([0, 0]))

In [73]:
testMat[:, 1] > 0

array([False,  True, False, False])

In [74]:
np.nonzero(testMat[:, 1] > 0)

(array([1]),)

In [75]:
np.nonzero(testMat[:, 1] > 0)[0]

array([1])

In [76]:
testMat[np.nonzero(testMat[:, 1] > 0)[0], :]
# two dim array

array([[0., 1., 0., 0.]])

In [77]:
# get one dim array
testMat[np.nonzero(testMat[:, 1] > 0)[0], :][0]

array([0., 1., 0., 0.])

***

In [78]:
def binSplitDataSet(dataSet, feature, value):
    mat0 = dataSet[np.nonzero(dataSet[:, feature] > value)[0], :]
    mat1 = dataSet[np.nonzero(dataSet[:, feature] <= value)[0], :]
    return mat0, mat1

In [79]:
mat0, mat1 = binSplitDataSet(testMat, 1, 0)
print(mat0)
print(mat1)

[[0. 1. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


numpy var

The variance is the average of the squared deviations from the mean, i.e., var = mean(abs(x - x.mean())**2).

In [80]:
def regLeaf(dataSet):
    return np.mean(dataSet[:, -1])

def regErr(dataSet):
    # np.var 求方差
    # D(X)=E{[X-E(X)]^2}
    return np.var(dataSet[:, -1]) * np.shape(dataSet)[0]

In [81]:
def createTree(dataSet, leafType=regLeaf, errType=regErr, ops=(1,4)):
    feat, val = chooseBestSplit(dataSet, leafType, errType, ops)
    if feat == None: return val
    retTree = {}
    retTree['spInd'] = feat
    retTree['spVal'] = val
    lSet, rSet = binSplitDataSet(dataSet, feat, val) 
    retTree['left'] = createTree(lSet, leafType, errType, ops) 
    retTree['right'] = createTree(rSet, leafType, errType, ops) 
    return retTree